language : android
android :
    components :
        - platform-tool
        - tool
        - android-14
        - build-tools-25.0.2
        - extra-android-m2repository
        - extra-google-m2repository
        - sys-img-armeabi-v7a-android-21

before_install:
    - chmod +x gradlew

before_script:
    - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

notifications :
    email : arnaudflaesch.dev@gmail.com